using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Instruction : MonoBehaviour
{
    // string: 머話辯벧W붙; GameObject: 머UIかτ
    public Dictionary<string, GameObject> currentInstructions {  get; private set; } = new Dictionary<string, GameObject>();
    public List<string> availabelInstructionName {  get; private set; } = new List<string>();
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    IEnumerator showInstruction(string instructionName, float delaySec)
    {
        if (currentInstructions.ContainsKey(instructionName))
        {
            Debug.LogError("머話霹w쩧{");
            yield break;
        }

        yield return new WaitForSeconds(delaySec);

        //if (availabelInstructionName)
    }



}
